-- Generated by scripts/seed-ideas.mjs from src/data/roadmap-ideas.json. Votes start at zero.
INSERT INTO suggestions (id, name, detail, primitive, normalized, status, source, votes, created_at) VALUES
  ('sound', 'Sound', 'UI sounds for taps, confirmations and errors, synthesized in the browser', NULL, 'sound', 'live', 'roadmap', 0, unixepoch()),
  ('depth', 'Depth', 'Perspective and 3D transforms you can turn and feel, as CSS', NULL, 'depth', 'live', 'roadmap', 0, unixepoch()),
  ('vision', 'Vision', 'See a palette the way people with color blindness do', 'color', 'vision', 'live', 'roadmap', 0, unixepoch()),
  ('chart', 'Chart', 'Categorical palettes for charts that stay distinct for every reader', 'color', 'chart', 'live', 'roadmap', 0, unixepoch()),
  ('dark', 'Dark', 'A dark theme derived from a light palette, with contrast kept', 'color', 'dark', 'live', 'roadmap', 0, unixepoch()),
  ('axes', 'Axes', 'A variable font''s axes on sliders, as font-variation-settings', 'type', 'axe', 'live', 'roadmap', 0, unixepoch()),
  ('features', 'Features', 'OpenType features such as tabular figures and ligatures, as CSS', 'type', 'feature', 'live', 'roadmap', 0, unixepoch()),
  ('masonry', 'Masonry', 'Packed card layouts with CSS grid, and the fallback for older browsers', 'grid', 'masonry', 'live', 'roadmap', 0, unixepoch()),
  ('divider', 'Divider', 'Wave, zigzag and curved section edges as SVG', 'shape', 'divider', 'live', 'roadmap', 0, unixepoch()),
  ('scroll', 'Scroll', 'Scroll-driven animation on the CSS timeline, previewed as you scroll', 'motion', 'scroll', 'live', 'roadmap', 0, unixepoch()),
  ('transition', 'Transition', 'View transitions between two states, played and exported as CSS', 'motion', 'transition', 'live', 'roadmap', 0, unixepoch());
