// Generates src/styles/tokens.css from src/data/tokens.json.
// tokens.json is the source of truth; never edit tokens.css by hand.
import { readFileSync, writeFileSync } from 'node:fs';

const root = new URL('../', import.meta.url);
const t = JSON.parse(readFileSync(new URL('src/data/tokens.json', root), 'utf8'));

const kebab = (s) => s.replace(/([a-z])([A-Z])/g, '$1-$2').replace(/([a-z])(\d)/g, '$1-$2').toLowerCase();
const px = (v) => (typeof v === 'number' ? `${v}px` : v);

const vars = [];
const phone = [];
const v = (name, value) => vars.push(`  --${name}: ${value};`);

for (const [k, val] of Object.entries(t.color)) v(kebab(k), val);

// Font stacks: the first family is served by the Astro Fonts API (see astro.config.mjs),
// which defines --font-hanken / --font-geist with metric-matched fallbacks.
v('sans', 'var(--font-hanken)');
v('mono', 'var(--font-geist)');

for (const [k, hue] of Object.entries(t.accent.hue)) {
  v(`accent-${k}`, hue === null ? 'var(--ink)' : t.accent.formula.replace('H', hue));
}

const { scale, ...space } = t.space;
for (const [k, val] of Object.entries(space)) {
  if (k.endsWith('Phone')) continue;
  v(kebab(k), px(val));
  if (space[`${k}Phone`] !== undefined) phone.push(`    --${kebab(k)}: ${px(space[`${k}Phone`])};`);
}
for (const [k, val] of Object.entries(t.size)) v(kebab(k), px(val));
for (const [k, val] of Object.entries(t.mark)) {
  if (typeof val === 'object') continue;
  if (k.endsWith('Phone')) continue;
  v(`mark-${kebab(k)}`, px(val));
  if (t.mark[`${k}Phone`] !== undefined) phone.push(`    --mark-${kebab(k)}: ${px(t.mark[`${k}Phone`])};`);
}
for (const [k, val] of Object.entries(t.radius)) v(`radius-${kebab(k)}`, px(val));
v('focus', t.border.focus);
v('focus-offset', px(t.border.focusOffset));
for (const [k, val] of Object.entries(t.shadow)) v(`shadow-${kebab(k)}`, val);
v('lift', t.motion.lift.transform);
v('dur-lift', `${t.motion.lift.duration}ms`);
v('ease-lift', t.motion.lift.easing);
v('dur-row', `${t.motion.row.duration}ms`);
v('dur-color', `${t.motion.color.duration}ms`);

const typeClasses = Object.entries(t.type).map(([k, s]) => {
  const decl = [];
  if (s.family === 'mono') decl.push('font-family: var(--mono)');
  decl.push(`font-size: ${s.size}px`);
  if (s.lineHeight !== undefined) decl.push(`line-height: ${s.lineHeight}`);
  if (s.tracking) decl.push(`letter-spacing: ${s.tracking}`);
  if (s.weight) decl.push(`font-weight: ${s.weight}`);
  if (s.transform) decl.push(`text-transform: ${s.transform}`);
  return `.t-${kebab(k)} { ${decl.join('; ')}; }`;
});

const css = `/* Generated by scripts/build-tokens.mjs from src/data/tokens.json. Do not edit. */
:root {
${vars.join('\n')}
}

@media (max-width: 719px) {
  :root {
${phone.join('\n')}
  }
}

${typeClasses.join('\n')}
`;

writeFileSync(new URL('src/styles/tokens.css', root), css);
