// Writes migrations/0002_roadmap_ideas.sql from src/data/roadmap-ideas.json. Refuses any
// idea already in the catalogue: the board is for what is not planned yet.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { runnerImport } from 'vite';

const root = fileURLToPath(new URL('../', import.meta.url));
const config = { configFile: false, root, logLevel: 'error', resolve: { alias: { '@': `${root}src` } } };
const { normalize, findInCatalogue } = (await runnerImport('/src/lib/requests.ts', config)).module;
const ideas = JSON.parse(readFileSync(`${root}src/data/roadmap-ideas.json`, 'utf8'));

const q = (v) => (v === null ? 'NULL' : `'${String(v).replaceAll("'", "''")}'`);
const rows = ideas.map((i) => {
  const clash = findInCatalogue(i.name, i.primitive);
  if (clash) throw new Error(`"${i.name}" is already in the catalogue as ${clash.primitive} / ${clash.name}`);
  return `  (${q(i.id)}, ${q(i.name)}, ${q(i.detail)}, ${q(i.primitive)}, ${q(normalize(i.name))}, 'live', 'roadmap', 0, unixepoch())`;
});
writeFileSync(
  `${root}migrations/0002_roadmap_ideas.sql`,
  `-- Generated by scripts/seed-ideas.mjs from src/data/roadmap-ideas.json. Votes start at zero.\nINSERT INTO suggestions (id, name, detail, primitive, normalized, status, source, votes, created_at) VALUES\n${rows.join(',\n')};\n`,
);
console.log(`${rows.length} roadmap ideas`);
